name: Main workflow

on:
  pull_request:
    types:
      - opened
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps -r requirements/requirements.lint.txt
      - name: Run linters
        run: make lint
