name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.linter.txt
      - name: Check editorconfig settings
        run: ec
      - name: Lint with flake8
        run: flake8 .
      - name: Lint with isort
        run: isort -qc .
